#!/bin/sh

# Ensure Sunshine can grab images from KMS
path_to_setcap=$(which setcap)
if [ -x "$path_to_setcap" ] ; then
  echo "$path_to_setcap cap_sys_admin+p /usr/local/bin/sunshine"
	$path_to_setcap cap_sys_admin+p $(readlink -f /usr/local/bin/sunshine)
fi
